module.exports = {
  ixdcLogoIc: '/icons/logo.png',
  arrowDown: '/icons/arrow_down.png',
  arrowUp: '/icons/arrow_up.png',
  rightArrow: '/icons/right_arrow.png',
  scanQr: '/icons/scan_qr.png',
  printIc: '/icons/print_green.png',
  printGray: '/icons/print_gray.png',
  signIc: '/icons/sign_in.png',
  resultSuccess: '/icons/result_success.png',
  resultWarning: '/icons/result_warning.png',
  resultFail: 'icons/result_fail.png',
  defaultAvatar: '/icons/default_avatar.png',
  resultFail: '/icons/result_fail.png',
}